### ISSUE TITLE
調査タスク: headless ui の使い方

### ISSUE THREAD

**Issue by uta8a** [hu-hicoder/hicord#3]
# 完了要件

scrapboxのページとして、使い方や参考になりそうなリンクをまとめる

# 手順

公式 https://headlessui.dev/ を参照

**Comment by keigooooo1065** [comment]
[hicord/調査タスク headless ui の使い方 - hicoder-developers](https://scrapbox.io/hicoder-developers/hicord%2F%E8%AA%BF%E6%9F%BB%E3%82%BF%E3%82%B9%E3%82%AF_headless_ui_%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9)

**Comment by uta8a** [comment]
@keigooooo1065 めちゃめちゃいい調査 👍 
closeしますね
